services:
  backend:
    build: 
      context: backend
    command: "fastapi dev app/main.py --host 0.0.0.0 --port 80"
    ports:
      - "8000:80"
    env_file:
      - ".env"
    volumes:
      - "./backend/alembic:/code/alembic"
      - "./backend/app:/code/app"
    depends_on:
      - db

  db:
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - "./tmp/pg_data:/var/lib/postgresql/data"
    env_file:
      - ".env"
